org: marcosotomac
service: api-s3

provider:
  name: aws
  runtime: python3.11
  # Default memory size for functions (default: 256MB)
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::967418674262:role/LabRole

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/crear-bucket
          method: post
          cors: true
          integration: lambda
  crear_directorio_bucket:
    handler: crear_directorio_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/crear-directorio
          method: post
          cors: true
          integration: lambda
  subir_archivo_bucket:
    handler: subir_archivo_bucket.lambda_handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /s3/bucket/subir-archivo
          method: post
          cors: true
          integration: lambda
